### ISSUE TITLE
Error in if (zero_count > zeroTolerance) { :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by CristianoCoelhoSilva** [skstavroglou/pattern_causality#1]
Hi guys, first I'd like to thank you for the amazing work on this implementation of pattern causality. I've been researching this topic at my university and am currently experimenting with this approach.

I would like to report an error I am encountering when executing a function from the package when the variable is set to E >= 3.

![Image](https://github.com/user-attachments/assets/08a9197d-5eb4-4c7b-8417-058079a5b5ad)

![Image](https://github.com/user-attachments/assets/50164227-cc37-42be-9678-218a2d1f649f)

When the comparison is X (Matrix or data frame of time series for the cause) and Y (Matrix or data frame of time series for the effect), the error does not occur.

![Image](https://github.com/user-attachments/assets/de90ee2a-f33a-4d30-825b-88f3a00ce143)

I ran a test where I imported the entire package to my machine and executed the functions directly, and the error did not occur.

![Image](https://github.com/user-attachments/assets/80ac5045-1b65-40d3-bd8b-14355b783d44)

Here are some examples of the data. It is important to highlight that the data was processed using dataset$ultimo <- c(NA, diff(log(dataset$ultimo))), possibly because there are negative values in the predictionY function.

![Image](https://github.com/user-attachments/assets/f3fb6910-ad40-45f1-b818-c8ed1767766e)

I am available for any questions.

Regards,
Cristiano C. da Silva
Researcher at FGV University.

**Comment by wanghui5801** [comment]
Hi Cristiano, can I see the version of `patterncausality` package? Theoretically they should work the same by the following install code:

```R
install.packages("patterncausality")
```

or

```shell
devtools::install_github("skstavroglou/pattern_causality")
```

We have updated the package last month to version 0.2.1, it might be a problem if they are in the different version.

**Comment by CristianoCoelhoSilva** [comment]
@wanghui5801, 

Indeed, the version is updated and the error persists, it could be something on my machine, since when I run it with a local installation it executes.

![Image](https://github.com/user-attachments/assets/bd88ba8c-68b9-4e89-916a-e2b49cd7b974)

**Comment by wanghui5801** [comment]
I see, it looks like you are using it on service? The `optimalParametersSearch` is based on `pcLightweight` function which is the core function in our package, if you can use it in local environments then it might be a problem on service, you can try this code again or reload the R environment to clean the cache

```R
devtools::install_github("skstavroglou/pattern_causality")
```

please have a check again and let me know if there is any further problem.

**Comment by CristianoCoelhoSilva** [comment]
@wanghui5801,

Thank you very much, I am conducting more tests, and I will inform you if anything comes up.

**Comment by lucaspordeus87** [comment]
Hello, @CristianoCoelhoSilva , did you overcome the problem? I am having a similar error.
